/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ActionController;
import controller.LoaderController;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import model.InvoiceHeader;
import model.InvoiceHeaderTableModel;
import model.InvoiceLine;
import model.InvoiceLineTableModel;

/**
 *
 * @author aahmed200
 */
public class SIGFrame extends javax.swing.JFrame {

    LoaderController loader;
    ActionController action_controller;

    /**
     * Creates new form SIGFrame
     */
    public SIGFrame() {
        super("Sales Invoice Generator");
        initComponents();
        this.loader = new LoaderController(this);
        this.action_controller = new ActionController(this.loader, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Allinv_table = new javax.swing.JTable();
        invoice_no = new javax.swing.JLabel();
        invoice_number_label = new javax.swing.JLabel();
        inv_table = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        inv_date = new javax.swing.JLabel();
        cus_name = new javax.swing.JLabel();
        inv_total = new javax.swing.JLabel();
        invc_itemlabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        inv_itemtable = new javax.swing.JTable();
        create_inc = new javax.swing.JButton();
        del_inv = new javax.swing.JButton();
        create_item = new javax.swing.JButton();
        del_item = new javax.swing.JButton();
        invoice_total_label = new javax.swing.JLabel();
        invoice_date_label = new javax.swing.JLabel();
        customer_name_label = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        load = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Sales Invoice Generator"); // NOI18N

        Allinv_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Date", "Customer", "Total"
            }
        ));
        Allinv_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Allinv_tableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Allinv_table);

        invoice_no.setText("InvoicenNumber");

        inv_table.setText("Invoice Table");

        inv_date.setText("Invoice Date");

        cus_name.setText("Customer Name");

        inv_total.setText("Invoice Total");

        invc_itemlabel.setText("Invoice Items");

        inv_itemtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Item Name", "Item Price", "Count", "Item Total"
            }
        ));
        inv_itemtable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inv_itemtableFocusLost(evt);
            }
        });
        inv_itemtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inv_itemtableMousePressed(evt);
            }
        });
        inv_itemtable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                inv_itemtableInputMethodTextChanged(evt);
            }
        });
        inv_itemtable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inv_itemtableKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(inv_itemtable);

        create_inc.setText("Create New Invoice");
        create_inc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_incActionPerformed(evt);
            }
        });

        del_inv.setText("Delete Invoice");
        del_inv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_invActionPerformed(evt);
            }
        });

        create_item.setText("Create New Item");
        create_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_itemActionPerformed(evt);
            }
        });

        del_item.setText("Delete Item");
        del_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_itemActionPerformed(evt);
            }
        });

        file_menu.setText("File");

        load.setMnemonic('L');
        load.setText("Load");
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });
        file_menu.add(load);

        save.setMnemonic('S');
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        file_menu.add(save);

        MenuBar.add(file_menu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(inv_table)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(invc_itemlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cus_name)
                                    .addComponent(inv_total)
                                    .addComponent(inv_date, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(invoice_no))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(invoice_number_label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(invoice_total_label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customer_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(invoice_date_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(create_inc)
                        .addGap(33, 33, 33)
                        .addComponent(del_inv, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(317, 317, 317)
                                .addComponent(del_item, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(create_item, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(inv_table))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoice_no)
                            .addComponent(invoice_number_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inv_date)
                            .addComponent(invoice_date_label))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cus_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inv_total)
                                .addGap(18, 18, 18)
                                .addComponent(invc_itemlabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(customer_name_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(invoice_total_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(create_inc)
                        .addComponent(del_inv))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(create_item)
                        .addComponent(del_item)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        action_controller.fillTables();
    }//GEN-LAST:event_loadActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        action_controller.save();
    }//GEN-LAST:event_saveActionPerformed

    private void create_incActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_incActionPerformed
        action_controller.showCreateInvoice(evt);
    }//GEN-LAST:event_create_incActionPerformed

    private void del_invActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_invActionPerformed
        action_controller.deleteInvoice(evt);
    }//GEN-LAST:event_del_invActionPerformed

    private void Allinv_tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Allinv_tableMousePressed
        action_controller.clickInvoiceTable(evt);
     }//GEN-LAST:event_Allinv_tableMousePressed

    private void create_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_itemActionPerformed
 action_controller.showCreateLine(evt);    }//GEN-LAST:event_create_itemActionPerformed

    private void inv_itemtableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inv_itemtableMousePressed
   action_controller.clickLineTable(evt);    }//GEN-LAST:event_inv_itemtableMousePressed

    private void del_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_itemActionPerformed
        action_controller.deleteInvoiceLine(evt);
    }//GEN-LAST:event_del_itemActionPerformed

    private void inv_itemtableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inv_itemtableInputMethodTextChanged
        System.out.println("view.SIGFrame.inv_itemtableInputMethodTextChanged()");
    }//GEN-LAST:event_inv_itemtableInputMethodTextChanged

    private void inv_itemtableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inv_itemtableKeyPressed
        System.out.println("view.SIGFrame.inv_itemtableKeyPressed()");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("view.SIGFrame.inv_itemtableKeyPressed(VK_ENTER)");
        }
    }//GEN-LAST:event_inv_itemtableKeyPressed

    private void inv_itemtableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inv_itemtableFocusLost
        System.out.println("view.SIGFrame.inv_itemtableFocusLost()");
    }//GEN-LAST:event_inv_itemtableFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Allinv_table;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton create_inc;
    private javax.swing.JButton create_item;
    private javax.swing.JLabel cus_name;
    private javax.swing.JLabel customer_name_label;
    private javax.swing.JButton del_inv;
    private javax.swing.JButton del_item;
    private javax.swing.JMenu file_menu;
    private javax.swing.JLabel inv_date;
    private javax.swing.JTable inv_itemtable;
    private javax.swing.JLabel inv_table;
    private javax.swing.JLabel inv_total;
    private javax.swing.JLabel invc_itemlabel;
    private javax.swing.JLabel invoice_date_label;
    private javax.swing.JLabel invoice_no;
    private javax.swing.JLabel invoice_number_label;
    private javax.swing.JLabel invoice_total_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem load;
    private javax.swing.JMenuItem save;
    // End of variables declaration//GEN-END:variables

    public JTable getInvoiceHeaderTable() {
        return this.Allinv_table;
    }
    
    public JTable getInvoiceLineTable() {
        return this.inv_itemtable;
    }
    
    public JLabel getInvoiceNumberLabel() {
        return this.invoice_number_label;
    }
    
    public JLabel getInvoiceDateLabel() {
        return this.invoice_date_label;
    }
    
    public JLabel getInvoiceCustomerNameLabel() {
        return this.customer_name_label;
    }
    
    public JLabel getInvoiceTotalLabel() {
        return this.invoice_total_label;
    }
}
